<?php

function batch_step_user_login(&$edit, $account)
{
    $usr = user_load($account->uid);
    $firstAccess = $usr->access === "0";
    
    $firstAccess = true;
    
    //in_array("administrator",$usr->roles) &&
    
    if($firstAccess){
        $batch = array(
            'title' => 'Configurando seu site.',
            'init_message' => "Iniciando configuração",
            'progress_message' => t('Completed @current of @total. (@percentage%)'),
            'operations' => array(
                array("activate_all_modules",array()),
                array("add_new_user", array('user@exemplo.com.br','123456')),
                array("cache_clean", array())
            ),
            'finished' => "Site configurado com sucesso",
            'file' => (drupal_get_path('module','batch_step') . DIRECTORY_SEPARATOR . 'batch_step.module')/* Arqyuvi que contem as funções que serão utilizadas em operations */
        );
        
        batch_set($batch);
    }
}


function activate_all_modules(&$context)
{
    $drush_script = "drush en -y devel epsacrop ckeditor features panels uuid views taxonomy_machine_name";
    
    shell_exec($drush_script);
     
    $context['message'] = "Ativando módulos.";
}

function add_new_user($email, $password, &$context)
{
    $drush_script = "drush user-create --password={$password} --mail={$email}";
    
    shell_exec($drush_script);
    
    $context['message'] =  "Criando usuário.";
}

function cache_clean(&$context)
{
    $drush_script = "drush cc all";
    
    shell_exec($drush_script);
    
    $context['message'] = "Limpando com cache.";
}